katalog/urls.py
# TODO: Implement Routings Herefrom django.urls import path
from katalog.views import show_katalog
from django.urls import path

app_name = 'katalog'

urlpatterns = [ # sbg path
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

from mywatchlist.models import mywatchlist

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include("mywatchlist.urls")),
    path('todolist/', include('todolist.urls'))
]

# TODO: Implement Routings Here

todolist/urls.py
# TODO: Implement Routings Herefrom django.urls import path
from todolist.views import show_todolist, update_task_status
from todolist.views import show_xml #customize to the name of the function created
from todolist.views import show_json # adjust the name of the function created
from todolist.views import show_json_by_id #customise the name of the function created
from todolist.views import show_xml_by_id #customise the name of the function created
from django.urls import path
from todolist.views import register #customize with the name of the function created
from todolist.views import login_user #customize with the name of the function created
from todolist.views import logout_user #customize with the name of the function created
from todolist.views import create_task, remove_task, add

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('xml/', show_xml, name='show_xml'), #customize the name of the function created
    path('json/', show_json, name='show_json'), #customise the name of the function created
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'), #customise the name of the function created
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'), #customise the name of the function created
    path('register/', register, name='register'), #customize with the name of the function created
    path('login/', login_user, name='login'), #customize with the name of the function created
    path('logout/', logout_user, name='logout'), #customize with the name of the function created
    path('create-task/', create_task, name='create_task'),
    path("update-task-status/<int:selected_id>", update_task_status, name="update_task_status"),
    path("remove-task/<int:selected_id>", remove_task, name="remove_task"),
    path('add/', add, name='add'),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    date = models.CharField(max_length=255)
    title = models.TextField()
    description = models.CharField(max_length=255)
    is_finished = models.BooleanField(default=False)

todolist/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from todolist.models import Task
from django.shortcuts import redirect
from django.urls import reverse
@login_required(login_url='/todolist/login/')

# Create your views here.
def show_todolist(request):
    context = {
        'name_of_user': request.user,
        'id_of_user': request.user.id,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)

def show_xml(request):
    data = Task.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json(request):
    data = Task.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request,id):
    data = Task.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def show_xml_by_id(request,id):
    data = Task.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # login first
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # create response
            response.set_cookie('last_login', str(datetime.datetime.now())) # create last_login cookie and add it to response
            return response
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login.html', context)

@login_required(login_url="/todolist/login/")
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url="/todolist/login/")
def create_task(request):
    if request.method == "POST":
        Field_title = request.POST.get("title")
        description = request.POST.get("description")
        answer = HttpResponseRedirect(reverse("todolist:show_todolist"))
        Task.objects.create(date=datetime.datetime.today(), title= Field_title, description=description, user=request.user,)
        return answer
    return render(request, "create_task.html")

@login_required(login_url="/todolist/login/")
def update_task_status(request, selected_id):
    selected_task = Task.objects.get(user=request.user, id=selected_id)
    answer = HttpResponseRedirect(reverse("todolist:show_todolist"))
    selected_task.is_finished = not selected_task.is_finished
    selected_task.save(update_fields=["is_finished"])

    return answer

@login_required(login_url="/todolist/login/")
def remove_task(request, selected_id):
    answer = HttpResponseRedirect(reverse("todolist:show_todolist"))
    selected_task = Task.objects.get(user=request.user, id=selected_id)
    selected_task.delete()
    return answer

@login_required(login_url="/todolist/login/")
def add(request):
    if request.method == "POST":
        Field_title = request.POST.get("title")
        description = request.POST.get("description")        
        Task.objects.create(date=datetime.datetime.today(), title= Field_title, description=description, user=request.user)
    return render(request, "todolist.html")

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
 
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
span.psw {
  float: right;
  padding-top: 16px;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 480px;
    width: 370px;
    background-color: rgba(255,255,255,0.13);
    position: fixed;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
button a{
    color: black;
    text-decoration: none;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>
  
</head>
<body>

    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <nav class="navbar  navbar-expand navbar-dark bg-dark py-2">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle Navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
              <li class="nav-item">
                <a class="nav-link" href="{% url 'todolist:show_todolist' %}">HOME</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'todolist:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
              </li>
            </ul>
          </div>
          <span class="navbar-text">
          </span>
        </div>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav" >
              <li class="nav-item" >
                <h3 class="navbar-text"> Hai {{name_of_user}} </h3>
              </li>
            </ul>
          </div>
      </nav>
      <class>
    <form method="post">
        {% csrf_token %}
    
        <table>
            <tr>
                <td>Title: </td>
                <td><input type="text" class="form-control" placeholder="Fill todo" name="title"></td>
            </tr>
                    
            <tr>
                <td>Description: </td>
                <td><input type="text" class="form-control" placeholder="fill description" name="description"></td>
            </tr>
        </table>
    
        <br>
        <button type="submit">Construct Task</button>
        <button><a href="{% url 'todolist:show_todolist' %}">Cancel</a></button>
    </form>

</body>
</html>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
 
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">

      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
span.psw {
  float: right;
  padding-top: 16px;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 480px;
    width: 370px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
@media screen and (max-height: 400px){
  form{
    height: 480px;
    width: 370px;
    background-color: white;
  
    
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
}

form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>
  
</head>
<body>

    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <nav class="navbar  navbar-expand navbar-dark bg-dark py-2">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle Navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav" me-auto mb-2 mb-lg-0 >
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todolist:register' %}">Register</a>
            </li>
          </ul>
        </div>
        <span class="navbar-text">
        </span>
      </div>
    </nav>
  
  
    <form method="POST" action="">
      {% csrf_token %}

        <label style="text-align: center;" for="uname"><b>Login Here</b></label>
        <input type="text" name="username" placeholder="Username" class="form-control">
        
        <input type="password" name="password" placeholder="Password" class="form-control">

        <button type="submit" class="btn btn-primary">Login</button>
        
        <div style="text-align: center;"><a href="{% url 'todolist:register' %}">Create Account</a> </div> 
    </form>
</body>
</html>
{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

 {% block content %}
    <head>
 
 <link rel="preconnect" href="https://fonts.gstatic.com">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
 <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
 <!--Stylesheet-->
 <style media="screen">
   *,
*:before,
*:after{
 padding: 0;
 margin: 0;
 box-sizing: border-box;
}
span.psw {
float: right;
padding-top: 16px;
}
body{
 background-color: #080710;
}
.background{
 width: 430px;
 height: 520px;
 position: absolute;
 transform: translate(-50%,-50%);
 left: 50%;
 top: 50%;
}
.background .shape{
 height: 200px;
 width: 200px;
 position: absolute;
 border-radius: 50%;
}
.shape:first-child{
 background: linear-gradient(
     #1845ad,
     #23a2f6
 );
 left: -80px;
 top: -80px;
}
.shape:last-child{
 background: linear-gradient(
     to right,
     #ff512f,
     #f09819
 );
 right: -30px;
 bottom: -80px;
}

    th {
      background-color: slategray;
      border-collapse: collapse;
      border: 5px solid black;
    }
    
h1 {
  color: whitesmoke;
}
h2 {
  color: whitesmoke;
}
body {
  min-height: 100vh;
  background: black;
}

body .container {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-wrap: wrap;
  max-width: 1200px;
  margin: 40px 0;
}

body .container .card {
  position: relative;
  min-width: 320px;
  height: 440px;
  box-shadow: inset 5px 5px 5px rgba(0, 0, 0, 0.2),
    inset -5px -5px 15px rgba(255, 255, 255, 0.1),
    5px 5px 15px rgba(0, 0, 0, 0.3), -5px -5px 15px rgba(255, 255, 255, 0.1);
  border-radius: 15px;
  margin: 30px;
  transition: 0.5s;
}

body .container .card .box {
  position: absolute;
  top: 20px;
  left: 20px;
  right: 20px;
  bottom: 20px;
  background: #2a2b2f;
  backdrop-filter: blur(10px);
  box-shadow: 0 0 40px rgba(8,7,16,0.6);
  border-radius: 15px;
  display: flex;
  justify-content: center;
  align-items: center;
  overflow: hidden;
  transition: 0.5s;
}

body .container .card .box:hover {
  transform: translateY(-50px);
}


body .container .card .box .content {
  padding: 20px;
  text-align: center;
}

body .container .card .box .content h2 {
  position: absolute;
  top: -10px;
  right: 30px;
  font-size: 8rem;
  color: rgba(255, 255, 255, 0.1);
}


body .container .card .box .content p {
  font-size: 1rem;
  font-weight: 300;
  color: rgba(255, 255, 255, 0.9);
  z-index: 1;
  transition: 0.5s;
}

body .container .card .box .content a {
  position: relative;
  display: inline-block;
  padding: 8px 20px;
  background: black;
  border-radius: 5px;
  text-decoration: none;
  color: white;
  margin-top: 20px;
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
  transition: 0.5s;
}

</style>

</head>
   <div class="background">
    <div class="shape"></div>
    <div class="shape"></div>
</div>
<nav class="navbar  navbar-expand navbar-dark bg-dark py-2">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle Navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:show_todolist' %}">HOME</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:create_task' %}">Add Task</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
        </li>
      </ul>
    </div>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav" >
        <li class="nav-item" >
          <h3 class="navbar-text"> Hai {{name_of_user}} </h3>
        </li>
      </ul>
    </div>
    <span class="navbar-text">
    </span>
  </div>
</nav>


  <div class="container" id = "abc"> </div>
  
  <button data-bs-toggle="modal" data-bs-target="#modal" style="width:20%; padding:2%;" >
    <h5 class="h5" style="color: black; text-align: center;">Create New Task</h5></button>
  
  <div class="modal fade" id="modal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog rounded-10">
      <div class="modal-content bg-dark">
        <div class="modal-header">
          <h1 class="modal-title fs-5" style="color: white;">Create a New Task!</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="form" method="POST" action="">
            {% csrf_token %}
          <table><tr><td>
            <div class="form-outline form-white mb-4">
              <input class="form-control" type="text" name="task_title" maxlength="70" required="" id="id_task_title" placeholder="Task Title!">
            </div></td></tr>
          
            <tr><td><div class="form-outline form-white mb-4">
              <textarea placeholder="Description of your task!" name="task_description" cols="50" rows="5" required="" class="form-control form-control-lg" id="id_task_description" spellcheck="false" ></textarea>
            </div></td></tr>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button data-bs-dismiss="modal" type="button" class="btn btn-outline-light btn-lg px-5" type="submit" value="Create!" id="create">Create!</button>
        </form>
        </div>
      </div>
    </div>
  </div>

<br>

<script>
  $(document).ready(() => {
    var user_id = '{{ id_of_user }}';
    
    $.ajax({
      url: "{% url 'todolist:show_json' %}", 
      method: 'GET',
      dataType: 'json',
      success: function(data) {
        var html_string = ""
           data.forEach((item) => {
             if (item.fields.user != user_id) {
              return;
             }
            html_string += `\n<div class="card">
            <div class="box">
              <div class="content">
                <p>${item.fields.date}</p>
                <h1>${item.fields.title}</h1>
                <p>${item.fields.description}</p>
                <p>Task Finish Status: ${item.fields.is_finished}</p>
                <a href="remove-task/`+ item.pk + `" title="">Remove Task</a>
                <a href="update-task-status/`+ item.pk + `" title="">Update Task</a>
              </div>
              </div>
          </div>`
           })
        var container= document.getElementById("abc");
        container.innerHTML = html_string
      }
    }) 
   });
  
   $("#modal").on("hidden.bs.modal", function() {
    $("#modal").find("#form").trigger("reset")
   })
   $("#create").on('click', function(e) {  
      e.preventDefault()
      $.post("{% url 'todolist:add' %}",
        {
          title: $('#id_task_title').val(),
          description: $('#id_task_description').val(),
          csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
        },
        function(data, status){
          $.ajax({
      url: "{% url 'todolist:show_json' %}", 
      method: 'GET',
      dataType: 'json',
      success: function(data) {
        var html_string = "";
        var user_id = '{{ id_of_user }}';
           data.forEach((item) => {
             if (item.fields.user != user_id) {
              return;
             }
            html_string += `\n<div class="card">
            <div class="box">
              <div class="content">
                <p>${item.fields.date}</p>
                <h1>${item.fields.title}</h1>
                <p>${item.fields.description}</p>
                <p>Task Finish Status: ${item.fields.is_finished}</p>
                <a href="remove-task/`+ item.pk + `" title="">Remove Task</a>
                <a href="update-task-status/`+ item.pk + `" title="">Update Task</a>
              </div>
              </div>
          </div>`
           })
        var container= document.getElementById("abc");
        container.innerHTML = html_string
      }
    }) 
   });

        }
      );
    
 </script>
{% endblock content %}